name: paginated_list
description: A Paginated List widget that displays a list of items using pagination.
version: 1.2.2
homepage: https://github.com/NazarenoCavazzon/flutter_paginated_list

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
